// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElFooter: typeof import("element-plus/es")["ElFooter"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSpace: typeof import("element-plus/es")["ElSpace"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    TheHeader: typeof import("./src/components/TheHeader.vue")["default"];
  }
}

export {};
